language: python
python:
    - "2.6"
    - "2.7"
install:
    - "pip install -r requirements.txt -r test-requirements.txt"
script:
    - tox
    - nosetests --with-coverage --cover-package=hello
notifications:
    email:
        recipients:
            - promisejohn@qq.com
            - 13902220007@139.com
            - 13802882681@139.com
            - 13802882645@139.com
            - 13802880354@139.com
        on_success: always
        on_failure: always

branches:
    only:
        - master
        - dev

after_success:
    - coveralls
