language: python
python:
    - "2.6"
    - "2.7"
install:
    - "pip install -r requirements.txt -r test-requirements.txt"
script:
    - tox
    - nosetests --with-coverage --cover-package=hello
notifications:
    email:
        recipients:
            - promise.john@gmail.com
            - promisejohn@qq.com
        on_success: always
        on_failure: always

after_success:
    - coveralls
